import type { Metadata } from "next";
import "./globals.css";
import ReduxProvider from "./store/reduxProvider";
import localFont from "next/font/local";
import CHeader from "./components/CHeader";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const raleway = localFont({
  src: [
    {
      path: "../../public/Fonts/Raleway-Black.ttf",
      style: "normal",
    },
    {
      path: "../../public/Fonts/Raleway-Bold.ttf",
      style: "normal",
      weight: "900",
    },
    {
      path: "../../public/Fonts/Raleway-ExtraBold.ttf",
      style: "normal",
    },
    {
      path: "../../public/Fonts/Raleway-ExtraLight.ttf",
      style: "normal",
    },
    {
      path: "../../public/Fonts/Raleway-Light.ttf",
      style: "normal",
    },
    {
      path: "../../public/Fonts/Raleway-Medium.ttf",
      style: "normal",
    },
    {
      path: "../../public/Fonts/Raleway-Regular.ttf",
      style: "normal",
    },
    {
      path: "../../public/Fonts/Raleway-SemiBold.ttf",
      style: "normal",
    },
  ],
  variable: "--font-raleway",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"
        />
      </head>
      <body className={`${raleway.variable}`}>
        <ReduxProvider>
          <CHeader />
          <main>{children}</main>
        </ReduxProvider>
      </body>
    </html>
  );
}
