export const Images = {
  gamePad: "/Images/joyStick.svg",
  keyboard: "/Images/keyboard.svg",
  screen: "/Images/screen.png",
  chair: "/Images/chair.png",
  star: "/Images/star.svg",
  fillStar: "/Images/fillStar.svg",
  jacket: "/Images/homeAndFurnitureCategory.png",
  bag: "/Images/bag.svg",
  tapRecorder: "/Images/tapRecorder.svg",
  table: "/Images/table.svg",
  mobilesCategory: "/Images/mobileCategory.png",
  fashionCategory: "/Images/fashionCategory.png",
  electronicsCategory: "/Images/electronicsCategory.png",
  homeAndFurniture: "/Images/homeAndFurnitureCategory.png",
  beautyCategory: "/Images/beautyCategory.png",
  babyCategory: "/Images/babyCategory.png",
  clothesOfferSlider: "/Images/clothesOffersSlider.jpeg",
  slider1: "/Images/slider1.png",
  slider2: "/Images/slider2.png",
  slider3: "/Images/slider3.png",
};
